Add OCP+ support
IBM/data-gate-cli pull request #44
Opened 2021-05-07 20:40 UTC by jensmueller-com

This pull request contains the following changes:

- Completely implement the [FYRE OCP+ APIs](https://w3.ibm.com/w3publisher/fyre/ocp/ocp-apis)

### Implementation

- All Click commands invoke a method of an instance of the `dg.lib.fyre.api_manager.OCPPlusAPIManager` class (= API manager).
- For each Click command, the API manager creates an instance of the corresponding request manager (package: `dg.lib.fyre.request_managers`).
- Each request manager executes a REST call and validates the response using the corresponding response manager (package: `dg.lib.fyre.response_managers`).
- Some request managers wrap the JSON response of the REST call in a data object that allows pretty-printing (package: `dg.lib.fyre.data`).

2021-06-02 17:16 UTC, choerst-ibm requested changes
Due to the sheer volume of this PR, I kept most of my comments to usability/documentation topics regarding the CLI functions. I also did one quick pass to look for any functional errors, but this looked good at first glance.

2021-06-02 19:00 UTC, jensmueller-com commented on dg/commands/fyre/cluster/add_worker_node.py
> +@click.option("--worker-node-num-cpus", help="Number of CPUs per worker node", type=click.IntRange(1, 16))
There is a variant of this command that already uses the right CPU and RAM values when aiming to use the cluster for Db2 Data Gate: `dg fyre cluster create-for-db2-data-gate`. Therefore, I would like to refrain from overwriting FYRE's default values as any other default values seem arbitrary to me.

2021-06-09 15:18 UTC, jensmueller-com commented on dg/commands/fyre/cluster/create.py
> +@optgroup.option("--ssh-key", help="SSH key")
I slightly changed the help text as the given SSH key is only installed on the infrastructure node.

2021-06-09 18:42 UTC, jensmueller-com commented on dg/commands/fyre/cluster/create_default.py
> +@click.option("--fyre-api-key", help="FYRE API key", required=True)
I changed the help text to "FYRE API key (https://fyre.svl.ibm.com/account)" in all 32 files specifying this option.

2021-06-09 18:50 UTC, jensmueller-com commented on dg/commands/fyre/cluster/create_for_db2_data_gate.py
> +@optgroup.option("--pull-secret", help="Pull secret")
Unfortunately, I have no idea what the semantics of this option is. The [OCP+ APIs](https://w3.ibm.com/w3publisher/fyre/ocp/ocp-apis) keep schtum about it.

2021-06-10 08:26 UTC, jensmueller-com commented
Christian (@choerst-ibm), could you please approve? Thanks!

2021-06-10 09:38 UTC, choerst-ibm approved these changes

2021-06-10 09:40 UTC, merged